name: Resuable Deploy
on: workflow_call # Allows this to be called from other workflow.    
jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Output information
          run: echo "Deploying & uploading..."
